### ISSUE TITLE
A couple of comments

### ISSUE THREAD

**Issue by CaseyCarter** [tcbrindle/NanoRange#14]
Hey @tcbrindle! Nice work on the library. Some thoughts I had while wandering:

* in `README.md`:
   > NanoRange is also missing the `tagged_tuple`/`tagged_pair` machinery from P0896; instead, `std::pair` and `std::tuple` are used as return types from algorithms.

   Don't bother: LEWG decided that they hate `tagged`, and requested that we replace all of the tagged return types with new named class types with named members.

* also in `README.md`:
   > Having said that, a couple of NanoRange selling points might be ... It's very much smaller.

   Have you done any comparative compile-time benchmarking?

* in `include/nanorange/detail/concepts/core.hpp`:

   > ```c++
   > // FIXME: Spec doesn't use remove_reference_t here, not sure if it should
   > template <typename Derived, typename Base>
   > NANO_CONCEPT DerivedFrom = std::is_base_of<Base, Derived>::value&&
   >    std::is_convertible<const volatile std::remove_reference_t<Derived>*,
   >                        const volatile std::remove_reference_t<Base>*>::value;
   > ```

   Only non-union class types (never reference types) can satisfy `is_base_of`.

**Comment by MikeGitb** [comment]
> Don't bother: LEWG decided that they hate tagged, and requested that we replace all of the tagged return types with new named class types with named members.

Off topic, but happy to hear that

**Comment by tcbrindle** [comment]
Hi Casey, thanks for the comments.

> Don't bother: LEWG decided that they hate `tagged`...

I saw this in the Rapperswil notes, but I've been on vacation and haven't had chance to update the README. I'll wait for you and Eric to come up with new names for the return types and update NanoRange accordingly.

> Have you done any comparative compile-time benchmarking?

I meant "it's much smaller" as a selling point because it allows NanoRange to (currently, at least) be useable as a single header, which is of course easier to drop into an existing project.

I'm wary of claiming that it compiles faster than Range-V3, because there's still a lot of stuff to be added (including all the views) which will of course slow down parsing. Having said that, I did a small amount of [testing](https://github.com/tcbrindle/NanoRange/wiki/Compile-times) which showed that  (on my system at least) it is currently a bit faster than Range-V3 in like-for-like tests (and CMCSTL2 as well, which surprised me -- I expected real concepts to be fastest). A friend of mine reported on Twitter that NanoRange compiled 2.5x faster than Range-V3 on his Android phone compiler, but I don't know what exactly he was comparing.

> Only non-union class types (never reference types) can satisfy `is_base_of`.

Thanks, that makes sense. I wish I could work out a way to make my variable templates short circuit like real concepts do, rather than having to use SFINAE on function return types to avoid hard errors, but nothing I've tried so far has worked better. 

I'm going to close this issue to keep things tidy, but feel free to comment further if you come across anything else. Thanks again.
