### ISSUE TITLE
`ostream_iterator` isn't `WeaklyIncrementable`?

### ISSUE THREAD

**Issue by ubsan** [tcbrindle/NanoRange#16]
This seems like it should be a bug - not being able to use `nano::copy` with `ostream_iterator`:

https://godbolt.org/g/bb1rxa

**Comment by tcbrindle** [comment]
Thanks @CaseyCarter. 

NanoRange does provide `nano::ostream_iterator` which should work, but doesn't because 

 * `array<int>` and  ostream_iterator<int>>` are not `IndirectlyComparable`, because
 * `ostream_iterator` is not `Readable`, because
 * P0896 didn't tell me to give it a `value_type`.

This seems to work in Range-V3 because that provides a specialisation of `std::iterator_traits`, which guess this is what NanoRange should do too.

@CaseyCarter, it intentional that `copy` requires its output iter to be `Readable`?

**Comment by CaseyCarter** [comment]
> `IndirectlyComparable`

`copy` should require `IndirectlyCopyable`, not `IndirectlyComparable`.

**Comment by tcbrindle** [comment]
https://github.com/tcbrindle/NanoRange/blob/master/include/nanorange/algorithm/copy.hpp#L65

...and there's the bug. Oops!

Thanks

**Comment by CaseyCarter** [comment]
I think the deeper bug here may be that `IndirectlyComparable` has a default argument for its `Relation` parameter which makes this mistake possible. You certainly won't be the last person to make this error. I'm using this bug as motivation to remove the default parameter in P0896R2.

**Comment by tcbrindle** [comment]
I'm blaming IDE autocomplete personally! But I think removing the default param would be a good idea.

**Comment by tcbrindle** [comment]
@ubsan As Casey pointed out, not being able to use `std::ostream_iterator` is by design in the ranges TS, but you should now be able to use `nano::ostream_iterator` instead: https://godbolt.org/g/GEaMNJ

Thanks for helping my uncover a bug, even if it wasn't the one you originally reported!

**Comment by ubsan** [comment]
@tcbrindle @CaseyCarter thanks so much! I've fixed my code.

The library is awesome, and I can't wait for ranges in the standard :)

**Comment by ericniebler** [comment]
In C++20, `std::ostream_iterator` will be `WeaklyIncrementable`.
