### ISSUE TITLE
nano::equal complains about comparing two ranges

### ISSUE THREAD

**Issue by cjdb** [tcbrindle/NanoRange#24]
I get some very strange behaviour when trying to use `nano::equal`, as shown below. `array_expression` is `EqualityComparable`, and this example works when I use both range-v3 and cmcstl2.

```cpp
void check_invariants(gsl::span<std::pair<array_expression, std::string_view>> const expressions,
   std::array<std::string_view, 3> const& names)
{
   Expects(nano::distance(expressions) == nano::distance(names));
   check_basic_invariants(expressions);
   CHECK(nano::equal(expressions, names, std::equal_to<>{}, &std::pair<array_expression, std::string_view>::second));
}
```

Offending expression: `nano::equal(expressions, names, std::equal_to<>{}, &std::pair<array_expression, std::string_view>::second)`.

Diagnostic: 
[error.txt](https://github.com/tcbrindle/NanoRange/files/2152206/error.txt)

**Comment by tcbrindle** [comment]
Hi @cjdb, that text file seems to be full of control codes that make it a bit hard to read (or maybe my Mac just doesn't like it) -- is there any chance you could try re-uploading it? (Or maybe put it up as a Gist?). Thanks.

**Comment by cjdb** [comment]
Ah, the colour codes are still present 😦 
How's this one?
[error.txt](https://github.com/tcbrindle/NanoRange/files/2152215/error.txt)

**Comment by tcbrindle** [comment]
That's much better, thanks!

I can see what's happening -- when testing the overloads of `equal`, it's checking to see whether `gsl::span` is an `Iterator`. To do this, it checks whether `iter_value_type_t` is valid, which causes `readable_traits_helper` to be instantiated. Unfortunately, `span` has *both* `value_type` and `element_type` members, so the instantiation of `readable_traits_helper` is ambiguous, which is a hard error.

(The ambiguity in the case of a type having both a `value_type` and `element_type` is by design -- see https://github.com/ericniebler/stl2/issues/562 -- but the hard error is my fault.)

This should be fixable by adding another partial specialisation of `readable_traits_helper` for when both member types are present, and properly constraining the other two.

**Comment by tcbrindle** [comment]
@cjdb  Hi Chris, can you give this a try and let me know if it's fixed?
