### ISSUE TITLE
forward_range overload for ranges::size evaluates `E` twice

### ISSUE THREAD

**Issue by cjdb** [tcbrindle/NanoRange#83]
Per [[range.prim.size]/1.3][1], `E` should be evaluated once, but I think it's evaluated twice. I'm also thinking it needs some `std::forward<T>(t)` somewhere too?

[1]: http://eel.is/c++draft/range.prim.size#1.3

**Comment by tcbrindle** [comment]
Just to make sure I'm looking in the right place, do you mean [here](https://github.com/tcbrindle/NanoRange/blob/master/include/nanorange/detail/ranges/primitives.hpp#L64)?

I think it's correct, at least as far as evaluations go: given a function call `nano::size(expr)`, the expression is evaluated (once) and the result is bound to `T&&` in the CPO's `operator()`. This result is then forwarded to the appropriate impl overload depending on the properties its type. Within the `forward_range` overload, we can't `std::forward` the provided argument because it gets used twice.

(There *is* a bug here though -- at some point the spec was changed to add `make-unsigned-like`, which we're not currently doing.)

**Comment by tcbrindle** [comment]
@cjdb I'm going to close this one as it's been a while, feel free to reopen if you want to persuade me I'm wrong :)
